<?php

namespace frontend\controllers;

use frontend\models\Address;

class AddressController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            //基于存取的权限控制器主要是要配置此过滤器
            'access' => [
                'class' => 'yii\filters\AccessControl',
                'rules' => [
                    [
                        'allow' => 'true',     //允许请求
                        'actions' => ['index','status','edit','delete'],        //允许请求的方法
                        'roles' => ['@']        //允许以登陆状态请求
                    ],
                ]
            ]
        ]; // TODO: Change the autogenerated stub
    }
    public function actionIndex()
    {
        $model=new Address();
//        var_dump(\Yii::$app->request->post());
//        var_dump($model->load(\Yii::$app->request->post(),''));exit;
        if($model->load(\Yii::$app->request->post(),'') && $model->validate()){
            $model->member_id=\Yii::$app->user->identity->id;
//            var_dump(\Yii::$app->request->post());exit;
            $model->save();
            return $this->redirect(['index']);
        }
        $datas=Address::find()->where(['member_id'=>\Yii::$app->user->identity->id])->all();
        return $this->render('address',['datas'=>$datas]);
    }
    public function actionStatus($id){
        $model=Address::findOne($id);
        $model->status=1;
        $model->save();
        return $this->redirect(['index']);
    }
    public function actionEdit($id){
        $model=Address::findOne(['id'=>$id]);
        //        var_dump(\Yii::$app->request->post());
        //        var_dump($model->load(\Yii::$app->request->post(),''));exit;
        if($model->load(\Yii::$app->request->post(),'') && $model->validate()){
            $model->member_id=\Yii::$app->user->identity->id;
            //            var_dump(\Yii::$app->request->post());exit;
            $model->save();
            return $this->redirect(['index']);
        }
        $datas=Address::find()->all();
        return $this->render('address',['datas'=>$datas,'model'=>$model]);
    }
    public function actionDelete($id){
        $model=Address::findOne(['id'=>$id]);
        $model->delete();
        echo TRUE;
    }
}
