<?php

namespace backend\filters;
use yii\base\ActionFilter;
use yii\helpers\Url;
use yii\web\HttpException;

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/9
 * Time: 21:01
 */
class AccessFilter extends ActionFilter{
//    public function beforeAction($action)
//    {
////        var_dump(!in_array($action->uniqueId, ['member/index','member/logout']));
////        exit;
//        //在user组件中的can传入的参数是权限的名称。为了判断当前以及登陆的用户是否有权限来执行此操作 ['admin/login'，'admin/logout','admin/code','admin/modify']
//        if (!\Yii::$app->user->can($action->uniqueId) && !in_array($action->uniqueId,['admin/login','admin/logout','admin/code','admin/welcome'])) {
//            $url=Url::to(['admin/welcome']);
//            echo '<h1>sorry~您没有权限：'."<a href=$url>返回主页</a></h1>";
//            exit;
//        }
//        return parent::beforeAction($action); // TODO: Change the autogenerated stub
//    }
    public function beforeAction($action)
    {
//        var_dump($action);exit;
        //$action->uniqueId;//当前访问的路由 admin/add
        if(!\Yii::$app->user->can($action->uniqueId)){
            //如果用户没有登陆，则引导用户到登陆页面
            if(\Yii::$app->user->isGuest){
                //一定不要忘记加send()方法
                return $action->controller->redirect(\Yii::$app->user->loginUrl)->send();
            }
            //没有该执行权限，抛出403状态码
            throw new HttpException(403,'对不起，您没有该执行权限');

        }
        //拦截 禁止访问
        //return false;//禁止
        //return true;//放行
        return parent::beforeAction($action);
    }

}