<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/17
 * Time: 15:28
 */

namespace backend\models;


use yii\base\Model;

class ModifyForm extends Model{
    public $password_confirm;
    public $password;
    public $beforePassword;

    public function rules()
    {
        return [
            [['beforePassword','password'],'required'],
            [['password_confirm'],
             'compare','compareAttribute'=>'password',
             'operator'=>'===','message'=>'两次密码必须一致']
        ];
        //return parent::rules(); // TODO: Change the autogenerated stub
    }
    public function attributeLabels()
    {
        return [
            'beforePassword'=>'旧密码',
            'password' => '新密码',
            'password_confirm'=>'确认密码'
        ];
    }
}